package com.resqnet.app.ui

import android.content.Intent
import android.net.Uri
import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.resqnet.app.data.api.*
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch

class RolePortalActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) { super.onCreate(savedInstanceState); setContent { MaterialTheme(colorScheme = darkColorScheme(background = Color(0xFF060911), surface = Color(0xFF0C1220), primary = Color(0xFF38BDF8))) { Portal({ url -> if (!url.isNullOrBlank()) startActivity(Intent(Intent.ACTION_VIEW, Uri.parse(url))) }, { startActivity(Intent(this, MainActivity::class.java)) }) } } }
}

@Composable private fun Portal(openMap: (String?) -> Unit, openProtection: () -> Unit) {
    var username by remember { mutableStateOf("") }; var password by remember { mutableStateOf("") }; var token by remember { mutableStateOf<String?>(null) }; var user by remember { mutableStateOf<SessionUser?>(null) }; var alerts by remember { mutableStateOf<List<EmergencyAlertDto>>(emptyList()) }; var userIncidents by remember { mutableStateOf<List<IncidentDto>>(emptyList()) }; var status by remember { mutableStateOf("Loading…") }; var error by remember { mutableStateOf<String?>(null) }; val scope = rememberCoroutineScope(); val auth = token?.let { "Bearer $it" }
    fun refresh() { if (auth == null || user == null) return; scope.launch { try { if (user!!.role == "USER") { userIncidents = ApiClient.api.getMyIncidents(auth).body().orEmpty(); status = "Emergency Protection: ACTIVE\nCrash Detection: ACTIVE\nNetwork: CONNECTED" } else { alerts = ApiClient.api.getPendingAlerts(auth).body().orEmpty(); status = if (user!!.role == "AMBULANCE") ApiClient.api.getAmbulance(user!!.resourceId!!, auth).body()?.let { "${it.code ?: it.id} · ${it.status ?: "UNAVAILABLE"}\nLocation: ${it.lat ?: "UNAVAILABLE"}, ${it.lng ?: "UNAVAILABLE"}\nAssignment: ${it.currentIncidentId ?: "NONE"}" } ?: "UNAVAILABLE" else ApiClient.api.getHospital(user!!.resourceId!!, auth).body()?.let { "${it.name ?: it.id}\n${it.status ?: "UNAVAILABLE"} · Trauma Level ${it.traumaLevel ?: "UNAVAILABLE"}\nEmergency capacity: ${it.emergencyCapacity ?: "UNAVAILABLE"}" } ?: "UNAVAILABLE" } } catch (e: Exception) { error = e.message ?: "Network unavailable" } } }
    LaunchedEffect(token) { if (token != null) while (true) { refresh(); delay(10_000) } }
    Column(Modifier.fillMaxSize().background(Color(0xFF060911)).padding(18.dp).verticalScroll(rememberScrollState())) {
        Text("RESQNET", color = Color.White, fontSize = 25.sp, fontWeight = FontWeight.Black, fontFamily = FontFamily.Monospace); Text(if (user == null) "OPERATIONS PORTAL SIGN-IN" else "${user!!.role.replace('_', ' ')} PORTAL", color = Color(0xFF38BDF8), fontSize = 11.sp, fontWeight = FontWeight.Bold); Spacer(Modifier.height(18.dp))
        if (user == null) { OutlinedTextField(username, { username = it }, label = { Text("Username") }, modifier = Modifier.fillMaxWidth(), singleLine = true); Spacer(Modifier.height(8.dp)); OutlinedTextField(password, { password = it }, label = { Text("Password") }, modifier = Modifier.fillMaxWidth(), singleLine = true, visualTransformation = androidx.compose.ui.text.input.PasswordVisualTransformation()); Spacer(Modifier.height(12.dp)); Button(onClick = { scope.launch { try { val r = ApiClient.api.login(LoginRequest(username, password)); if (r.isSuccessful && r.body() != null) { token = r.body()!!.token; user = r.body()!!.user; error = null } else error = "Login failed: ${r.code()} — check username and password" } catch (e: Exception) { error = "Cannot reach backend at ${ApiClient.getBaseUrl()}: ${e.message}" } } }, modifier = Modifier.fillMaxWidth()) { Text("LOGIN") }; Spacer(Modifier.height(8.dp)); Text("Backend: ${ApiClient.getBaseUrl()}", color = Color(0xFF94A3B8), fontSize = 10.sp); Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.spacedBy(8.dp)) { OutlinedButton(onClick = { ApiClient.setEnvironment(AppEnvironment.EMULATOR); error = "Emulator endpoint selected" }, modifier = Modifier.weight(1f)) { Text("EMULATOR") }; OutlinedButton(onClick = { ApiClient.setEnvironment(AppEnvironment.LOCAL_LAN); error = "LAN endpoint selected" }, modifier = Modifier.weight(1f)) { Text("PHONE / LAN") } }; Text("Emulator uses 10.0.2.2. A physical phone must use the same Wi-Fi as 192.168.1.11.", color = Color(0xFF94A3B8), fontSize = 10.sp); Text("Demo: user1, ambulance1, hospital1. Password is server-configured.", color = Color(0xFF94A3B8), fontSize = 11.sp) }
        else { Card(colors = CardDefaults.cardColors(containerColor = Color(0xFF0C1220)), shape = RoundedCornerShape(12.dp)) { Column(Modifier.padding(16.dp)) { Text("CURRENT STATUS", color = Color(0xFF94A3B8), fontSize = 11.sp); Text(status, color = Color.White, fontFamily = FontFamily.Monospace) } }; Spacer(Modifier.height(12.dp)); if (user!!.role == "USER") { Text("EMERGENCY RESPONSE STATUS", color = Color(0xFFEF4444), fontWeight = FontWeight.Black); Button(onClick = openProtection, modifier = Modifier.fillMaxWidth()) { Text("OPEN CRASH PROTECTION") }; if (userIncidents.isEmpty()) Text("No incidents associated with this account.", color = Color(0xFF94A3B8), modifier = Modifier.padding(vertical = 16.dp)); userIncidents.forEach { incident -> Card(colors = CardDefaults.cardColors(containerColor = Color(0xFF20111A)), modifier = Modifier.fillMaxWidth().padding(vertical = 6.dp)) { Column(Modifier.padding(14.dp)) { Text("🚨 ACCIDENT DETECTED", color = Color(0xFFEF4444), fontWeight = FontWeight.Black); Text("Incident: ${incident.incidentId ?: incident.id}\nStatus: ${incident.status ?: "UNAVAILABLE"}\nAmbulance: ${incident.assignedAmbulance ?: incident.ambulanceId ?: "UNAVAILABLE"}\nHospital: ${incident.assignedHospital ?: incident.hospitalId ?: "UNAVAILABLE"}", color = Color.White, fontFamily = FontFamily.Monospace) } } } } else { Text(if (user!!.role == "AMBULANCE") "EMERGENCY DISPATCHES" else "INCOMING TRAUMA ALERTS", color = Color(0xFFEF4444), fontWeight = FontWeight.Black); if (alerts.isEmpty()) Text("No pending targeted alerts.", color = Color(0xFF94A3B8), modifier = Modifier.padding(vertical = 16.dp)); alerts.forEach { alert -> Alert(alert, user!!.role, openMap) { action, reason -> scope.launch { val r = when(action) { "accept" -> ApiClient.api.acceptDispatch(alert.incidentId, auth!!); "reject" -> ApiClient.api.rejectDispatch(alert.incidentId, auth!!, mapOf("reason" to reason)); else -> ApiClient.api.acknowledgeHospitalAlert(alert.incidentId, auth!!) }; if (!r.isSuccessful) error = "Action failed"; refresh() } } } }; OutlinedButton(onClick = { token = null; user = null; alerts = emptyList(); userIncidents = emptyList() }, modifier = Modifier.fillMaxWidth()) { Text("LOG OUT") } }
        error?.let { Text(it, color = Color(0xFFEF4444), modifier = Modifier.padding(top = 10.dp)) }
    }
}

@Composable private fun Alert(alert: EmergencyAlertDto, role: String, openMap: (String?) -> Unit, run: (String, String) -> Unit) { var rejecting by remember { mutableStateOf(false) }; var reason by remember { mutableStateOf("") }; Card(colors = CardDefaults.cardColors(containerColor = Color(0xFF20111A)), shape = RoundedCornerShape(12.dp), modifier = Modifier.fillMaxWidth().padding(vertical = 8.dp)) { Column(Modifier.padding(16.dp)) { Text(if (role == "AMBULANCE") "🚨 EMERGENCY DISPATCH" else "🚨 INCOMING TRAUMA ALERT", color = Color(0xFFEF4444), fontWeight = FontWeight.Black); Text("${alert.priority ?: "UNAVAILABLE"} · ${alert.incidentId}", color = Color.White, fontFamily = FontFamily.Monospace); Text("Location: ${alert.accidentLatitude ?: "UNAVAILABLE"}, ${alert.accidentLongitude ?: "UNAVAILABLE"}", color = Color(0xFFCBD5E1)); Text(alert.helpMessage ?: "NOT PROVIDED", color = Color(0xFFCBD5E1)); Text(if (role == "AMBULANCE") "Distance: ${alert.distanceKm ?: "UNAVAILABLE"} km · ETA: ${alert.etaMinutes ?: "UNAVAILABLE"} min" else "Incoming ambulance: ${alert.incomingAmbulance ?: "UNAVAILABLE"} · ETA: ${alert.etaMinutes ?: "UNAVAILABLE"} min\nPatient information: ${alert.patientCount ?: "NOT PROVIDED"}", color = Color(0xFFCBD5E1)); OutlinedButton(onClick = { openMap(alert.mapUrl) }) { Text("OPEN ACCIDENT LOCATION") }; if (role == "AMBULANCE") { Row { Button(onClick = { run("accept", "") }, colors = ButtonDefaults.buttonColors(containerColor = Color(0xFF10B981))) { Text("ACCEPT") }; Spacer(Modifier.width(8.dp)); OutlinedButton(onClick = { rejecting = !rejecting }) { Text("REJECT") } }; if (rejecting) { OutlinedTextField(reason, { reason = it }, label = { Text("Rejection reason") }); Button(onClick = { if (reason.isNotBlank()) run("reject", reason) }) { Text("CONFIRM REJECTION") } } } else Button(onClick = { run("ack", "") }, colors = ButtonDefaults.buttonColors(containerColor = Color(0xFF10B981))) { Text("ACKNOWLEDGE ALERT") } } } }
